import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore';
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Message from '../components/message'
import { db } from '../utils/firebase';

export default function Home() {
  // Get all posts
  const [allPost, setAllPost] = useState([])

  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPost(snapshot.docs.map((doc) => ({...doc.data(), id:doc.id})))
    })
    return unsubscribe;
  }

  useEffect(()=> {
    getPosts()
  }, [])

  console.log(allPost)

  return (
    <div>
      <Head>
        <title>Creative Minds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='md:my-12 my-6 text-lg'>
        <h2>See what are people are saying</h2>
        {
          allPost.map((post) => (
            <Message {...post} key={post.id}>
              <Link href={{pathname: `/${post.id}`, query: {...post}}}>
                <button className='text-sm'>{post.comments?.length > 0 ? post.comments?.length : 0} comments</button>
              </Link>
            </Message>
          ))
        }
      </div>
    </div>
  )
}
